/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-11-30 15:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>后台管理登录</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/info.css\">\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"> \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" body,td,div\r\n");
      out.write(" {\r\n");
      out.write("   font-size:12px;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<BODY>\r\n");
      out.write("<FORM id=\"info\" name=\"info\"  method=\"post\" action=\"LoginInSystem.action\">\r\n");
      out.write("<DIV id=UpdatePanel1>\r\n");
      out.write("<DIV>\r\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=900 align=center border=0>\r\n");
      out.write("\t<TBODY>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD style=\"HEIGHT: 105px\"><IMG src=\"images/login_1.jpg\" border=0></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD background=images/login_2.jpg height=300>\r\n");
      out.write("\t\t\t<TABLE height=300 cellPadding=0 width=900 border=0>\r\n");
      out.write("\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD colSpan=2 height=35>&nbsp;</TD></TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD width=360></TD>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t<TABLE cellSpacing=0 cellPadding=2 border=0>\r\n");
      out.write("\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\" width=80>登 录 名：</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\" width=150><INPUT id=\"params.manager_name\" name=\"params.manager_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${params.manager_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"WIDTH: 130px\" name=txtName></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\" width=370>\r\n");
      out.write("\t\t\t\t\t\t\t\t<SPAN  id=\"RequiredFieldValidator1\" style=\"FONT-WEIGHT: bold; VISIBILITY: hidden; COLOR: white\">请输入登录名</SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\">登录密码：</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\"><INPUT id=\"params.manager_pass\" name=\"params.manager_pass\"   style=\"WIDTH: 130px\" \r\n");
      out.write("\t\t\t\t\t\t\t  type=\"password\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<SPAN id=\"RequiredFieldValidator2\" style=\"FONT-WEIGHT: bold; VISIBILITY: hidden; COLOR: white\">请输入密码</SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\">验 证 码：</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<INPUT id=\"params.random\" name=\"params.random\" style=\"WIDTH: 60px\" name=txtcode>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"Random.jsp\" width=\"50\" valign=\"middle\" style=\"cursor:pointer;vertical-align:middle\" title=\"换一张\" id=\"safecode\" border=\"0\" onClick=\"reloadcode()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD style=\"HEIGHT: 28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<SPAN id=\"RequiredFieldValidator3\" style=\"FONT-WEIGHT: bold; VISIBILITY: hidden; COLOR: white\">请输入验证码</SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD colspan=\"2\" id=\"loginTip\" style=\"HEIGHT:22px;color:orange\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tip}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"loginInBtn\"  style=\"border:0px;cursor:pointer\" src=\"images/login_button.gif\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD>\r\n");
      out.write("\t\t\t\t<IMG src=\"images/login_3.jpg\" border=0>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</TBODY>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</DIV>\r\n");
      out.write("</DIV>\r\n");
      out.write("</FORM>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t//实现验证码点击刷新\r\n");
      out.write("\tfunction reloadcode(){\r\n");
      out.write("\t\tvar verify=document.getElementById('safecode');\r\n");
      out.write("\t\tverify.setAttribute('src','Random.jsp?'+Math.random());\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tvar loginInBtn = $(\"#loginInBtn\");\r\n");
      out.write("\t\tvar manager_name = $(\"#params\\\\.manager_name\");\r\n");
      out.write("\t\tvar manager_pass = $(\"#params\\\\.manager_pass\");\r\n");
      out.write("\t\tvar random = $(\"#params\\\\.random\");\r\n");
      out.write("\t\tvar loginTip = $(\"#loginTip\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloginInBtn.bind('click',function(){\r\n");
      out.write("\t\t\tif(manager_name.val()==''||manager_pass.val()==''||random.val()==''){\r\n");
      out.write("\t\t\t\tloginTip.html(\"用户名、密码和验证码不能为空！\")\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#info\").submit();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*var regInBtn = $(\"#regInBtn\");\r\n");
      out.write("\t\tregInBtn.bind('click',function(){\r\n");
      out.write("\t\t\twindow.location.href=\"reg.jsp\";\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t});*/\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
